version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
    open-pull-requests-limit: 20
    groups:
      mshv:
        patterns:
          - "mshv-*"
      wasm-tools:
        patterns:
          - "wasmparser"
          - "wit-parser"
          - "wit-component"
  - package-ecosystem: "cargo"
    directory: "/src/tests/rust_guests"
    schedule:
      interval: "daily"
      time: "03:00"
    labels:
      - "kind/dependencies"
      - "area/guest"
    open-pull-requests-limit: 5
