[package]
name = "mesh_host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mesh_host"
path = "src/main.rs"

[dependencies]
hyperlight-mesh = { path = "../../hyperlight_mesh" }
hyperlight-host = { workspace = true,  default-features = false, features = ["mesh","kvm"] }
