// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
pub mod hyperlight {
    use super::*;
    pub mod generated {
        use super::*;
        mod parameter_value_generated;
        pub use self::parameter_value_generated::*;
        mod parameter_type_generated;
        pub use self::parameter_type_generated::*;
        mod return_type_generated;
        pub use self::return_type_generated::*;
        mod return_value_generated;
        pub use self::return_value_generated::*;
        mod hlint_generated;
        pub use self::hlint_generated::*;
        mod hluint_generated;
        pub use self::hluint_generated::*;
        mod hllong_generated;
        pub use self::hllong_generated::*;
        mod hlulong_generated;
        pub use self::hlulong_generated::*;
        mod hlfloat_generated;
        pub use self::hlfloat_generated::*;
        mod hldouble_generated;
        pub use self::hldouble_generated::*;
        mod hlstring_generated;
        pub use self::hlstring_generated::*;
        mod hlbool_generated;
        pub use self::hlbool_generated::*;
        mod hlvecbytes_generated;
        pub use self::hlvecbytes_generated::*;
        mod hlvoid_generated;
        pub use self::hlvoid_generated::*;
        mod function_call_result_generated;
        pub use self::function_call_result_generated::*;
        mod parameter_generated;
        pub use self::parameter_generated::*;
        mod function_call_generated;
        pub use self::function_call_generated::*;
        mod function_call_type_generated;
        pub use self::function_call_type_generated::*;
        mod error_code_generated;
        pub use self::error_code_generated::*;
        mod guest_error_generated;
        pub use self::guest_error_generated::*;
        mod hlsizeprefixedbuffer_generated;
        pub use self::hlsizeprefixedbuffer_generated::*;
        mod log_level_generated;
        pub use self::log_level_generated::*;
        mod guest_log_data_generated;
        pub use self::guest_log_data_generated::*;
    }
}
